name: List Inactive Branches

on:
  push:
    branches:
      - "*"

jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git fetch --all --prune
          git for-each-ref --format='%(refname:short) %(committerdate:iso)' refs/remotes | while read branch date; do
            if [[ "$(git log -n 1 --since='2 days ago' "$branch" | wc -l)" -eq 0 ]]; then
              git push https://github.com/$GITHUB_REPOSITORY --delete "$branch" --quiet --access-token ${{secrets.ACCESS_TOKEN}}
            fi
          done

      - name: List remaining branches
        run: |
          git branch -a
