name: List Inactive Branches

on:
  push:
    branches:
      - "*"

jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch --all --prune
          git for-each-ref --format='%(refname:short) %(committerdate:iso)' refs/remotes | while read branch date; do
            if [[ "$(git log -n 1 --since='4 days ago' "$branch" | wc -l)" -eq 0 ]]; then
              git config --global user.email "shubham.varneshiya@kcsitglobal.com"
              git config --global user.name "shubhamkcs"
              git push origin --delete "$branch"
              echo "Branch $branch Deleted !!"
            fi
          done

      - name: List remaining branches
        run: |
          git branch -a
