name: Delete In active branches

on:
  push:
    branches:
      - "*"
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Inactive Branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch --prune --unshallow

          cutoff_date=$(date --date='1 days ago' +%Y-%m-%d)
          prDetails=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&sort=updated&direction=desc")


          for pr in $(echo "$prDetails" | jq -r '.[] | @base64'); do

            pr_data=$(echo "$pr" | base64 --decode)
            pr_number=$(echo "$pr_data" | jq -r '.number')
            branch_name=$(echo "$pr_data" | jq -r '.head.ref')

            merged_Status=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq '.merged')
            last_Commit_Date=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/commits/$branch_name" | jq -r '.commit.author.date')

            echo "last_Commit_Date : $last_Commit_Date"
            echo "Cut of date : $cutoff_date"
            echo "Branch Name : $branch_name"
            echo "Last commmit < cut of date"
            
              if [ "$cutoff_date" < "$last_Commit_Date" ]; then
                  echo "Deleting branch $branch_name"
              fi

          done

      - name: List remaining branches
        run: |
          echo "********* Remaining branches *********"
          git branch -a
