name: Delete Remote and Local Branch

on:
  push:
    branches:
      - "*"

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches (forcefully)
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch --prune --unshallow
          cutoff_date=$(date --date='3 days ago' +%Y-%m-%d)
          git for-each-ref --format='%(refname:short) %(committerdate:short)' refs/remotes/origin | \
            while read branch commit_date; do
              if [[ "$commit_date" < "$cutoff_date" ]]; then
               branch=$(echo "$branch" | sed 's/\borigin\b//g')
               echo "modified branch name is : $branch"
               git push origin --delete $branch
              fi
            done

      - name: List remaining branches
        run: |
          git branch -a
