name: Delete In active branches

on:
  push:
    branches:
      - "*"
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Inactive Branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          echo "something is happened!!"
          git fetch --prune --unshallow
          cutoff_date=$(date --date='1 days ago' +%Y-%m-%d)
          pr_details=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&sort=updated&direction=desc")
          echo "something is happened!!again..."     
          for pr in $(echo "$pr_details" | jq -r '.[] | @base64'); do
              pr_data=$(echo "$pr" | base64 --decode)
              pr_number=$(echo "$pr_data" | jq -r '.number')
              branch_name=$(echo "$pr_data" | jq -r '.head.ref')
              echo "Again something is happened!!"
              echo "PR No : $pr_data"
              echo "branch_name : $branch_name"
                    
      - name: List remaining branches
        run: |
          echo "********* Remaining branches *********"
          git branch -a
