name: Delete Remote and Local Branch

on:
  push:
    branches:
      - "*"

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches (forcefully)
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch origin --prune +refs/remotes/*:refs/remotes/*
          
          git for-each-ref --format='%(refname:short) %(committerdate:iso)' refs/remotes | while read branch date; do
            if [[ "$(git log -n 1 --since='3 days ago' "$branch" | wc -l)" -eq 0 ]]; then
              git config --global user.email "shubham.varneshiya@kcsitglobal.com"
              git config --global user.name "shubhamkcs"
              
              echo "Branch is : $branch"
            fi
          done

      - name: List remaining branches
        run: |
          git branch -a

