name: Delete Remote and Local Branch

on:
  push:
    branches:
      - "*"

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch origin --prune +refs/remotes/*:refs/remotes/*

      - name: List branches before deletion
        run: |
          git branch -a

      - name: Delete inactive branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git for-each-ref --format='%(refname:short) %(committerdate:iso)' refs/remotes | while read branch date; do
            if [[ "$(git log -n 1 --since='4 days ago' "$branch" | wc -l)" -eq 0 ]]; then
              echo "Processing branch: $branch"
              git config --global user.email "shubham.varneshiya@kcsitglobal.com"
              git config --global user.name "shubhamkcs"

              git push origin --delete -f "$branch"

              local_branch=$(echo "$branch" | sed 's|refs/remotes/origin/||')
              git branch -D "$local_branch"
              echo "Deleted both remote and local branch: $branch"
            fi
          done

      - name: List remaining branches
        run: |
          git branch -a
