name: List Inactive Branches

on:
  push:
    branches:
      - "*"

jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Setup configuration
        run: |
          git config --global user.email "shubham.varneshiya@kcsitglobal.com"
          git config --global user.name "shubhamkcs" 
          USER_EMAIL = git config --global user.email
          echo "configuration Email :  $USER_EMAIL"

      - name: Fetch all branches
        run: |
          git fetch --all --prune
          git for-each-ref --format='%(refname:short) %(committerdate:iso)' refs/remotes | while read branch date; do
            if [[ "$(git log -n 1 --since='2 days ago' "$branch" | wc -l)" -eq 0 ]]; then
              # git branch -D "$branch"
              # git push origin --delete "$branch" 
              echo "Branch $branch Deleted !!"
            fi
          done

      - name: List remaining branches
        run: |
          git branch -a
