name: Delete In active branches

on:
  push:
    branches:
      - "*"

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Inactive Branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git fetch --prune --unshallow

          cutoff_date=$(date --date='15 days ago' +%Y-%m-%d)

          git for-each-ref --format='%(refname:short) %(committerdate:short)' refs/remotes/origin | \
            while read branch commit_date; do
              branch=$(echo "$branch" | sed 's/origin\///')
              if [[ "$commit_date" < "$cutoff_date" ]] && \
                 [[ "$branch" != "main" && "$branch" != "QA" && "$branch" != "Shubham_Dev" ]]; then 
                 git push origin --delete "$branch"
                 echo "$branch is deleted successfully!!"
              fi
            done

      - name: List remaining branches
        run: |
          echo "********* Remaining branches *********"
          git branch -a
