name: Delete In active branches

on:
  push:
    branches:
      - "*"
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Inactive Branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          echo "Yes Its done !!"
          git fetch --prune --unshallow

          cutoff_date=$(date --date='1 days ago' +%Y-%m-%d)
          merged_prs=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&sort=updated&direction=desc")
          echo "I'm going in loop"      
                  
          for pr in $(echo "$merged_prs" | jq -r '.[] | @base64'); do
            pr_data=$(echo "$pr" | base64 --decode)
            pr_number=$(echo "$pr_data" | jq -r '.number')
            echo "inside loop dude!"
            branch_name=$(echo "$pr_data" | jq -r '.head.ref')
            echo "branch name $branch_name | PR NO : $pr_number"
          done

      - name: List remaining branches
        run: |
          echo "********* Remaining branches *********"
          git branch -a
