name: List Inactive Branches

on:
  push:
    branches:
      - "*"

jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List inactive branches
        run: |
          # Get the current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo "Current date: $CURRENT_DATE"
          # Iterate through branches
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            # Check if the branch is older than 15 days
            LAST_COMMIT_DATE=$(git log -n 1 --format=%cd --date=format:'%Y-%m-%d' "$branch")
            if [[ $(date -d "$LAST_COMMIT_DATE" +%s) -lt $(date -d "$CURRENT_DATE -15 days" +%s) ]]; then
              echo "Branch '$branch' was last active on '$LAST_COMMIT_DATE'."
            fi
          done
