name: List Inactive Branches

on:
  push:
    branches:
      - "*"

jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List inactive branches
        run: |
          # Get the current date and calculate 2 days ago in YYYY-MM-DD format
          CURRENT_DATE=$(date -u +"%Y-%m-%d")
          TWO_DAYS_AGO=$(date -u -d "2 days ago" +"%Y-%m-%d")

          # Fetch all branches
          git fetch --all --prune

          # List branches inactive for the last 2 days
          git for-each-ref --format='%(committerdate:short) %(refname:short)' refs/heads | while read -r date branch; do
              if [ "$(date -d "$date" +%Y-%m-%d)" \< "$TWO_DAYS_AGO" ]; then
                  echo "$branch"
              fi
          done

          echo "$branch"
