name: Delete In active branches

on:
  push:
    branches:
      - "*"
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Inactive Branches
        env:
          ACTIONS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          echo "Yes Its done !!"
          git fetch --prune --unshallow

          cutoff_date=$(date --date='1 days ago' +%Y-%m-%d)
          prDetails=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&sort=updated&direction=desc")
                  
          for pr in $(echo "$prDetails" | jq -r '.[] | @base64'); do
            pr_data=$(echo "$pr" | base64 --decode)
            pr_number=$(echo "$pr_data" | jq -r '.number')
            branch_name=$(echo "$pr_data" | jq -r '.head.ref')

            merged_Status=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq '.merged')
            last_Commit_Date=$(curl -s -H "Authorization: Bearer ${{secrets.PERSONAL_ACCESS_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/commits/$branch_name" | jq -r '.commit.author.date')

            echo "branch name : $branch_name"
            echo "Last Commit Date : $last_Commit_Date"
            echo "cutoff_date : $cutoff_date"

            echo "if[['$last_Commit_Date' < '$cutoff_date']]"

            if [[ "$last_Commit_Date" < "$cutoff_date" && "$merged_Status" == "true" ]]; then
              echo "Deleting branch $branch_name"
              #git branch -D "$branch_name"
            fi
          done

      - name: List remaining branches
        run: |
          echo "********* Remaining branches *********"
          git branch -a
