name: Close Stale Pull Requests

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  close-stale-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Open Pull Requests
        id: get_pulls
        run: |
          echo "Analyzing..."
          PR_LIST=$(curl -s -H "Authorization: Bearer ${{secrets.PAT_WITH_PR}}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
          for pr in $(echo "${PR_LIST}" | jq -r '.[] | select(.created_at <= "1 days ago" and .state == "open" and .user.login != "dependabot[bot]") | .number'); do
            curl -X PATCH -H "Authorization: Bearer ${{secrets.PAT_WITH_PR}}" -H "Content-Type: application/json" -d '{"state":"closed"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$pr"
            echo "PR closed successfully.."
          done
