name: Fetch Open Pull Requests

on:
  push:
    branches:
      - "*"

jobs:
  fetch-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Open Pull Requests
        id: get_pulls
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/pulls
          owner: "kcs-shubhamvarneshiya"
          repo: "jesttest"
          state: open 
          token: ${{secrets.PAT_WITH_PR}}

      - name: Display Open Pull Requests
        run: |
          echo "Open Pull Requests:"
          echo "${{ steps.get_pulls.outputs.data[0].body }}" 
