name: SonarQube report analysis and Quality gate

on:
  push:
    branches:
      - '*'

  pull_request: 
      branches:
      - '*'

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests with coverage
      run: npm test --coverage
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./coverage

    - name: SonarQube Scan
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner \
          -Dsonar.host.url=http://sonarqube.kcspl.in:9000 \
          -Dsonar.login=82937a40b7dbb37782bacb338c7bca84a24196e9 \
          -Dsonar.projectKey=QulityGateTest \
          -Dsonar.sources=./src \
          -Dsonar.javascript.lcov.reportPaths=./coverage/icov.info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Check SonarQube Quality Gate
      run: |
        echo "checking quality gate status..."
        STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=QulityGateTest" -u "4bfeceb86030431b89e0f94ac01e996405e8f016" | jq -r '.projectStatus.status')
       
        if [ "$STATUS" != "OK" ]; then
          echo "SonarQube Quality Gate Failed !!"
          exit 1
        else
          echo "SonarQube Quality Gate passed !!" 
        fi
