name: Get Commit and PR Count

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  count-commits-and-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count Commits per Branch
        run: |
          branches=$(git branch -r | grep -v '\->' | sed 's/origin\///' | tr -d '[:space:]')

          for branch in $branches; do
            commit_count=$(git rev-list --count origin/$branch)
            echo "Branch $branch has $commit_count commit(s)."
          done

      - name: Name of branches
        run: |
          branches=$(git branch -r | grep -v '\->' | sed 's/origin\///' | tr -d '[:space:]')
          echo "Branches in the repository:"
          echo "$branches"
